name: Collect Repository Metrics

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  collect-metrics:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Collect metrics from GitHub API
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NODE_ENV: production
        run: |
          # Run the metrics collection script
          node scripts/collect-metrics.js
          
      - name: Notify completion
        if: success()
        run: |
          echo "Metrics collection completed successfully"
          
      - name: Handle failure
        if: failure()
        run: |
          echo "Metrics collection failed"
          # Could add notification logic here